services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tw-diary
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
